### ISSUE TITLE
add 1345 to LPC_DEVICE_TYPE LPCtypes[]

### ISSUE THREAD

**Issue by ghost** [FEDEVEL/openrex-nxp-lpc13xx#1]
I needed to add this to make it correct for my OpenRex. 
{ 0x28010541, "1345", 32, 8, 8, 4096, SectorTable_17xx, CHIP_VARIANT_LPC13XX },

Lower here should be 16 instead of 8, referring to http://www.nxp.com/documents/user_manual/UM10524.pdf#I22.5.1680366
{ 0x8020543, "1347", 64, 8, **16**, 4096, SectorTable_17xx, CHIP_VARIANT_LPC13XX },

**Comment by robertferanec** [comment]
Adrian, please could you make a pull request? I will update it.
PS:  "{ 0x8020543" I guess, this should be "{ 0x28020543"
